package com.edso.resume.lib.common;

public class DbKeyConfig {
    public static final String ID = "id";
    public static final String FULL_NAME = "full_name";
    public static final String PHONE_NUMBER = "phone_number";
    public static final String EMAIL = "email";
    public static final String DATE_OF_BIRTH = "date_of_birth";
    public static final String HOMETOWN = "hometown";
    public static final String SCHOOL_ID = "school_id";
    public static final String SCHOOL_NAME = "school_name";
    public static final String JOB_ID = "job_id";
    public static final String JOB_NAME = "job_name";
    public static final String LEVEL_JOB_ID = "level_job_id";
    public static final String LEVEL_JOB_NAME = "level_job_name";
    public static final String CV = "cv";
    public static final String SOURCE_CV_ID = "source_cv_id";
    public static final String SOURCE_CV_NAME = "source_cv_name";
    public static final String HR_REF = "hr_ref";
    public static final String DATE_OF_APPLY = "date_of_apply";
    public static final String CV_TYPE = "cv_type";
    public static final String STATUS_CV_ID = "status_cv_id";
    public static final String STATUS_CV_NAME = "status_cv_name";
    public static final String NAME_SEARCH = "name_search";
    public static final String CREATE_AT = "create_at";
    public static final String UPDATE_AT = "update_at";
    public static final String LAST_APPLY = "last_apply";
    public static final String TAGS = "tags";
    public static final String GENDER = "gender";
    public static final String NOTE = "note";
    public static final String EVALUATION = "evaluation";
    public static final String UPDATE_STATUS_CV_AT = "update_status_cv_at";
    public static final String UPDATE_STATUS_CV_BY = "update_status_cv_by";
    public static final String CREATE_BY = "create_by";
    public static final String UPDATE_BY = "update_by";
    public static final String NAME = "name";
    public static final String SSN = "ssn";
    public static final String REASON = "reason";
    public static final String UPDATE_BLACKLIST_AT = "update_blacklist_at";
    public static final String UPDATE_BLACKLIST_BY = "update_blacklist_by";
    public static final String ID_PROFILE = "id_profile";
    public static final String TIME = "time";
    public static final String ADDRESS = "address";
    public static final String FORM = "form";
    public static final String INTERVIEWER = "interviewer";
    public static final String INTERVIEWEE = "interviewee";
    public static final String CONTENT = "content";
    public static final String QUESTION = "question";
    public static final String COMMENTS = "comments";
    public static final String TIME_START = "time_start";
    public static final String TIME_FINISH = "time_finish";
    public static final String CHECK = "check";
    public static final String N_LOOP = "n_loop";
    public static final String ACTION = "action";
    public static final String USERNAME = "username";
    public static final String TYPE = "type";
    public static final String DEPARTMENT_ID = "department_id";
    public static final String DEPARTMENT_NAME = "department_name";


}
