package com.edso.resume.lib.common;

public class ErrorCodeDefs {
    public static final int ERROR_CODE_SYSTEM_BUSY = -1;
    public static final int ID = -1;
    public static final int ERROR_CODE_OK = 0;
    public static final int ERROR_CODE_FAILED = 1;
    public static final int ERROR_CODE_ACCOUNT_NOT_EXISTED = 11;
    public static final int INVALID_JWT_SIGNATURE = 176;
    public static final int INVALID_JWT_TOKEN = 177;
    public static final int ERR_CODE_TOKEN_TIME_OUT = 178;
    public static final int UNSUPPORTED_JWT_TOKEN = 179;
    public static final int JWT_CLAIMS_EMPTY = 180;

    public static final int EMAIL = 200;
    public static final int PHONE_NUMBER = 201;
    public static final int SSN = 202;
    public static final int NAME = 203;
    public static final int REASON = 204;
    public static final int ID_PROFILE = 205;
    public static final int TIME = 206;
    public static final int ADDRESS = 207;
    public static final int FORM = 208;
    public static final int INTERVIEWER = 209;
    public static final int INTERVIEWEE = 210;
    public static final int CONTENT = 211;
    public static final int QUESTION = 212;
    public static final int COMMENTS = 213;
    public static final int EVALUATION = 214;
    public static final int STATUS = 215;
    public static final int TIME_START = 216;
    public static final int TIME_FINISH = 217;
    public static final int IMAGE = 218;
    public static final int STATUS_CV = 219;
    public static final int USERNAME = 220;
    public static final int COMMENT = 221;
    public static final int FILE = 222;
    public static final int FULL_NAME = 223;
    public static final int GENDER = 224;
    public static final int DATE_OF_BIRTH = 225;
    public static final int HOMETOWN = 226;
    public static final int SCHOOL = 227;
    public static final int LEVEL_SCHOOL = 228;
    public static final int JOB = 229;
    public static final int LEVEL_JOB = 230;
    public static final int SOURCE_CV = 231;
    public static final int HR_REF = 232;
    public static final int DATE_OF_APPLY = 233;
    public static final int TALENT_POOL = 234;
    public static final int DEPARTMENT = 235;
    public static final int TITLE = 236;
    public static final int TYPE_OF_JOB = 237;
    public static final int QUANTITY = 238;
    public static final int DETAIL_OF_SALARY = 239;
    public static final int FROM = 240;
    public static final int TO = 241;
    public static final int JOB_DESCRIPTION = 242;
    public static final int REQUIREMENT_OF_JOB = 243;
    public static final int DEAD_LINE = 244;
    public static final int MANAGERS = 245;
    public static final int DESCRIPTION = 246;
    public static final int NUMBER_OF_PROFILE = 247;
    public static final int LAST_APPLY = 248;
    public static final int RECRUITMENT = 249;
    public static final int MAIL_REF = 250;
    public static final int DATE = 251;
    public static final int FLOOR = 252;
    public static final int TYPE = 253;
    public static final int NOTE = 254;
    public static final int SEND_EMAIL_TO_INTERVIEWEE = 255;
    public static final int SEND_EMAIL_TO_INTERVIEWER = 256;
    public static final int OFFICE_NAME = 257;
    public static final int INTERVIEW_PROCESS = 258;


}
